server:
  port: 8081

spring:
  application:
    name: user-service

  profiles:
    include: common

  # Allow bean definition overriding and circular references temporarily
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/documind
    username: documind
    password: documind123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 20000

  data:
    redis:
      host: localhost
      port: 6379
      password: documind123
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  flyway:
    schemas: users
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false

# Service-specific logging
logging:
  level:
    com.documind.user: DEBUG
    org.springframework.security: INFO
  file:
    name: logs/user-service.log

# JWT specific for user service
jwt:
  secret: ${JWT_SECRET:documind-user-service-secret-key-change-in-production}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days
